### ISSUE TITLE
使用“adversarial_train”训练多人，比使用“ordinary_train”得到的效果（和原始音频的相似性）更好吗？

### ISSUE THREAD

**Issue by EinsQiang** [MingruiYuan/SpoofSV#1]
谢谢你的分享。

看完你的论文，我猜测使用“adversarial_train”的效果是更好的。我想要把你的思想应用的其他TTS模型上。所有想确认一下这个问题：

使用“adversarial_train”训练多人，比使用“ordinary_train”得到的效果（和原始音频的相似性）更好吗？

**Comment by MingruiYuan** [comment]
Hi, as for your question, now I have to say that we do not compare the spoofing effects of TTS model with and without adversarial training due to limited time. We use adversarial training as we think that it can generate (mel)-spectrograms that are more similar to original speech. And we reference [this paper](https://arxiv.org/pdf/1709.08041.pdf) which compares the feature distribution of synthetic speech with and without adversarial training.
But what you said is an issue that should be considered. For this repository you can disable adversarial training by not using the parameter "--adversarial". In this case the training command becomes `python -u main.py train_text2mel -C config.json -T ${ctime} --save_spectrogram ` or `python -u main.py train_ssrn -C config.json -T ${ctime} --save_spectrogram `. Models are saved at `./checkpoints/conditional/not_adversarial/${ctime}/`. 
Next I will also perform this experiment.  We can share the results later.

**Comment by EinsQiang** [comment]
非常感谢😁
